###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Alvey, CS165
# Author:
#     Ethan Holden
# Summary:
#     This program prompts the user for product information by 
#     first asking for the name, the description, the weight, 
#     and the price. If the price is not valid it propts for 
#     the price again. Then it ask the user for three different 
#     displays to choose from the first shows the product based 
#     on advertising needs. The second shows it for inventory 
#     needs and the last shows a receipt of the item if it were 
#     to be purchased.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

