###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Alvey, CS165
# Author:
#     Ethan Holden
# Summary:
#     This program uses the class Product to prompt the user 
#     for the name of a product, a description, its weight, 
#     and its price. It then asks the user for a number that 
#     corrisponds to a display setting and then dispplays 
#     either: the advertisment with the name, price, and 
#     description; the Inventory entry with the price, name, 
#     and weight; or the Receipt that displays the name, and a 
#     breakdown of the total cost, including the price, sales 
#     tax, and shipping cost. All of which have been calculated 
#     by the class methods.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

