###############################################################
# Program:
#     Checkpoint 11b, Class Templates
#     Brother Alvey, CS165
# Author:
#     Ethan Holden
# Summary:
#     Summaries are not necessary for checkpoint assignments.
###############################################################


a.out : check11b.cpp pair.h
	g++ check11b.cpp
	tar -cf check11b.tar makefile *.h *.cpp

clean : 
	rm a.out *.tar
