###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Alvey, CS165
# Author:
#     Ethan Holden
# Summary:
#     This program takes 4 different classes to store and 
#     display customer and product information. The Address 
#     class stores the street, city, state, and zip code. The 
#     Cusomer class stores the customer's name as well as the 
#     address associated with that customer. The product class 
#     stores the  the product, its description as well as its 
#     price and weight and even caulates the sales, tax, 
#     shipping, and total cost of the item. Then finally the 
#     Order stores the order placed by the customer, which 
#     customer ordered it and how many and even calculates the 
#     total cost of the order.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

