###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Alvey, CS165
# Author:
#     Ethan Holden
# Summary:
#     This program has four different classes that work together 
#     to store the information needed for an order to a 
#     company's website. The Address class stores the full 
#     address of the customer. The Customer class stores the 
#     customer's name and associates it with the coorisponding 
#     address. The Product class stores the product information 
#     and provides ways to access the various data in different 
#     formats. Then the Order class keeps the order all together 
#     and provides access to the information needed to send out 
#     the order.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

